name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'CHANGELOG.md'
      - '.github/workflows/release.yml'

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [
          "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", 
          "pypy-3.8", "pypy-3.9", "pypy-3.10", "pypy-3.11"]
        exclude:
          - os: macos-latest
            python-version: "3.7"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Nox
        run: pip install Nox

      - name: Test
        run: nox --sessions test --force-python ${{ steps.setup-python.outputs.python-path }}

