name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'CHANGELOG.md'
      - '.github/workflows/release.yml'

jobs:
  matrix:
    name: ${{ matrix.os }}-${{matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [
          "3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t",
          "pypy-3.9", "pypy-3.10", "pypy-3.11"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      # avoid setup-python noise on macOS
      - name: Clear pre-baked pip cache
        if: runner.os == 'macOS'
        run: rm -rf ~/Library/Caches/pip

      - name: Set up Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Nox
        run: pip install Nox

      - name: Test
        run: nox --sessions test --force-python ${{ steps.setup-python.outputs.python-path }}

  build-wheel:
    name: Build wheel for legacy-Python containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
          if-no-files-found: error
          retention-days: 1

  container:
    name: old-${{matrix.python-version}}
    needs: build-wheel
    runs-on: ubuntu-latest
    container: python:${{matrix.python-version}}-slim
    strategy:
      fail-fast: false
      matrix: 
        python-version: [ '3.7', '3.8' ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: System Setup
      shell: bash
      run: |
        pip install pytest

    - name: Download wheel
      uses: actions/download-artifact@v4
      with:
        name: wheel
        path: dist
        
    - name: Test
      shell: bash
      run: |
        pip install dist/*.whl
        python -m pytest

